Models/Client.cs
using System.ComponentModel.DataAnnotations;

namespace PushNotificationCore.Models
{
    public class Client
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "You must fill the input")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Its an exception")]
        public bool SimularException { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace PushNotificationCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PNotify.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PushNotificationCore.Models
{
    public static class PNotify
    {
        public static void Success(string msg)
        {
            
        }
    }
}

Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PushNotificationCore.Controllers
{
    public class BaseController : Controller
    {
        public void MessageSuccess(string message)
        {                 
            this.TempData.Add("success", message);
        }
        public void MessageError(string message)
        {
            this.TempData.Add("error", message);
        }
        public void MessageInfo(string message)
        {
            this.TempData.Add("info", message);
        }
    }
}

Controllers/ClientsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PushNotificationCore.Data;
using PushNotificationCore.Models;

namespace PushNotificationCore.Controllers
{
    public class ClientsController : BaseController
    {
        private readonly PushNotifyDbContext _context;

        public ClientsController(PushNotifyDbContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clients.ToListAsync());
        }

       

        // GET: Clients/Create
        public IActionResult Create()
        {
            MessageInfo("Your about to create a client");
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,SimularException")] Client Client)
        {
            if (ModelState.IsValid)
            {
                if(!Client.SimularException){
                    _context.Add(Client);
                    await _context.SaveChangesAsync();                
                    MessageSuccess("Registred Successfuly !");
                }
                else{
                    MessageError("Exception !"); 
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(Client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Client = await _context.Clients.FindAsync(id);
            if (Client == null)
            {
                return NotFound();
            }
            return View(Client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,SimularException")] Client Client)
        {
            if (id != Client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(Client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(Client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(Client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Client = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Client == null)
            {
                return NotFound();
            }

            return View(Client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Client = await _context.Clients.FindAsync(id);
            _context.Clients.Remove(Client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Clients.Any(e => e.Id == id);
        }
    }
}

Views/Clients/Create.cshtml
@model PushNotificationCore.Models.Client

@{
    ViewData["Title"] = "Create";
}
<h1 class="page-header">
    <a class="anchorjs-link " href="#overview" aria-label="Anchor link for: overview"
       data-anchorjs-icon="" style="font-family: anchorjs-icons;
font-style: normal; font-variant: normal; font-weight: normal;
line-height: inherit; position: absolute; margin-left: -1em;
padding-right: 0.5em;"></a>
    New Client
</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" asp-for="Name" placeholder="Enter your name" autocomplete="off">
            </div>

            <div class="checkbox">
                <label>
                    <input asp-for="SimularException"> Simulate Exception
                </label>
            </div>
            <div>
                <a asp-action="Index" class="btn btn-default">Cancel</a>
                <button type="submit" class="btn btn-success pull-right">Submit</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
   @* @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}*@
}

Views/Clients/Delete.cshtml
@model PushNotificationCore.Models.Client

@{
    ViewData["Title"] = "Delete";
}


<h1 class="page-header" id="overview">
    <a class="anchorjs-link " href="#overview"
       aria-label="Anchor link for: overview" data-anchorjs-icon=""
       style="font-family: anchorjs-icons; font-style: normal;
       font-variant: normal; font-weight: normal; line-height: inherit;
      position: absolute; margin-left: -1em; padding-right: 0.5em;">
    </a>Delete Client
</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" asp-for="Name" disabled="disabled">
            </div>

            <div class="checkbox">
                <label>
                    <input asp-for="SimularException" disabled="disabled"> Simular Exception
                </label>
            </div>
            <div>
                <a asp-action="Index" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-danger pull-right">Delete</button>
            </div>

        </form>
    </div>
</div>

Views/Clients/Edit.cshtml
@model PushNotificationCore.Models.Client

@{
    ViewData["Title"] = "Edit";
}


<h1 class="page-header" id="overview"><a class="anchorjs-link " href="#overview" aria-label="Anchor link for: overview" data-anchorjs-icon="" style="font-family: anchorjs-icons; font-style: normal; font-variant: normal; font-weight: normal; line-height: inherit; position: absolute; margin-left: -1em; padding-right: 0.5em;"></a>Edit Clients</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" asp-for="Name" placeholder="Entre com Name" autocomplete="off">
            </div>

            <div class="checkbox">
                <label>
                    <input asp-for="SimularException"> Simular Exception
                </label>
            </div>
            <div>
                <a asp-action="Index" class="btn btn-default">Cancelar</a>
                <button type="submit" class="btn btn-success pull-right">Edit</button>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clients/Index.cshtml
@model IEnumerable<PushNotificationCore.Models.Client>

@{
    ViewData["Title"] = "Index";
}
<h1 class="page-header" id="overview"><a class="anchorjs-link " href="#overview" aria-label="Anchor link for: overview" data-anchorjs-icon="" style="font-family: anchorjs-icons; font-style: normal; font-variant: normal; font-weight: normal; line-height: inherit; position: absolute; margin-left: -1em; padding-right: 0.5em;"></a>List of clients</h1>
<div class="row">
    <div class="col-xs-12" style="margin-bottom:20px">
        <a class="btn btn-success btn-lg pull-right" asp-action="Create">New Client</a>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-striped">
        <colgroup>
            <col class="col-xs-1">
            <col class="col-xs-7">
        </colgroup>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th scope="row"> <code>@item.Id</code> </th>
                    <td>@item.Name</td>
                    <td>
                        <a class="btn btn-default btn-sm" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Shared/Components/AdminMensagens/Default.cshtml
@{
    var temp = TempData.FirstOrDefault();

    if (temp.Value != null)
    {
        <ul id="msgs" class="list-unstyled hide">
            <li  data-classe="@temp.Key.ToString()">@temp.Value.ToString()</li>
        </ul>
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PushNotificationCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Clients" asp-action="Index" class="navbar-brand">PushNotificationCore</a>
            </div>
        </div>
    </nav>    

    <div class="container body-content">
        @await Component.InvokeAsync("AdminMensagens")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - PushNotificationCore</p>
        </footer>
    </div>

    <environment include="Development">

        <script src="~/lib/pnotify/PNotify.js"></script>
        <script src="~/lib/pnotify/PNotifyButtons.js"></script>
        <script src="~/lib/pnotify/PNotifyConfirm.js"></script>
        <script src="~/lib/pnotify/PNotifyMobile.js"></script>

        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">

        <script src="~/lib/pnotify/PNotify.js"></script>
        <script src="~/lib/pnotify/PNotifyButtons.js"></script>
        <script src="~/lib/pnotify/PNotifyConfirm.js"></script>
        <script src="~/lib/pnotify/PNotifyMobile.js"></script>

        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>